### ISSUE TITLE
How to receive the notification ?

### ISSUE THREAD

**Issue by aidonsnous** [Namanyahillary/dusupay-test#1]
THe classes you have developped are really wonderfull, thanks for that. I have not only seen the code that is processing the request sent by TRANSACTION STATUS NOTIFICATION when one sent a payment request.

If I understand well the documentation, it is said that the response only comes there and then if you are in a sandbox but when you are live as you sent the response may not come there and then but you will receive it via the :

>  "dusupay_successURL":"(optional)https://domain.com/myIPNCallbackURL",
So what is missing is the example of code that will handle this request from  callbackURL sent by dusupay.

**Comment by Namanyahillary** [comment]
These have been added [here](https://github.com/Namanyahillary/dusupay-test/tree/master/api/php/transaction_notifications)
